
import { God, Difficulty } from './types';

// Data parsed from the provided CSV file
export const HINDU_GODS: God[] = [
  { id: '1', names: { English: 'Shiva', Hindi: 'शिव', Telugu: 'శివుడు', Kannada: 'ಶಿವ', Tamil: 'சிவன்', Malayalam: 'ശിവൻ' } },
  { id: '2', names: { English: 'Vishnu', Hindi: 'विष्णु', Telugu: 'విష్ణువు', Kannada: 'ವಿಷ್ಣು', Tamil: 'விஷ்ணு', Malayalam: 'വിഷ്ണു' } },
  { id: '3', names: { English: 'Lakshmi', Hindi: 'लक्ष्मी', Telugu: 'లక్ష్మి', Kannada: 'ಲಕ್ಷ್ಮೀ', Tamil: 'லட்சுமி', Malayalam: 'ലക്ഷ്മി' } },
  { id: '4', names: { English: 'Saraswati', Hindi: 'सरस्वती', Telugu: 'సరస్వతి', Kannada: 'ಸರಸ್ವತಿ', Tamil: 'சரஸ்வதி', Malayalam: 'സരസ്വതി' } },
  { id: '5', names: { English: 'Krishna', Hindi: 'कृष्ण', Telugu: 'కృష్ణుడు', Kannada: 'ಕೃಷ್ಣ', Tamil: 'கிருஷ்ணன்', Malayalam: 'കൃഷ്ണൻ' } },
  { id: '6', names: { English: 'Rama', Hindi: 'राम', Telugu: 'రాముడు', Kannada: 'ರಾಮ', Tamil: 'ராமன்', Malayalam: 'രാമൻ' } },
  { id: '7', names: { English: 'Hanuman', Hindi: 'हनुमान', Telugu: 'హనుమంతుడు', Kannada: 'ಹನುಮಾನ್', Tamil: 'ஹனுமான்', Malayalam: 'ഹനുമാൻ' } },
  { id: '8', names: { English: 'Ganesha', Hindi: 'गणेश', Telugu: 'గణేశుడు', Kannada: 'ಗಣೇಶ', Tamil: 'விநாயகர்', Malayalam: 'ഗണേശൻ' } },
  { id: '9', names: { English: 'Durga', Hindi: 'दुर्गा', Telugu: 'దుర్గ', Kannada: 'ದುರ್ಗಾ', Tamil: 'துர்கா', Malayalam: 'ദുർഗ്ഗ' } },
  { id: '10', names: { English: 'Kartikeya', Hindi: 'कार्तिकेय', Telugu: 'కార్తికేయ', Kannada: 'ಕಾರ್ತಿಕೇಯ', Tamil: 'கார்த்திகேயன்', Malayalam: 'കാർത്തികേയൻ' } },
  { id: '11', names: { English: 'Agni (Fire)', Hindi: 'अग्नि', Telugu: 'అగ్ని', Kannada: 'ಅಗ್ನಿ', Tamil: 'அக்னி', Malayalam: 'അഗ്നി' } },
  { id: '12', names: { English: 'Vayu (Wind)', Hindi: 'वायु', Telugu: 'వాయువు', Kannada: 'ವಾಯು', Tamil: 'வாயு', Malayalam: 'വായു' } },
  { id: '13', names: { English: 'Indra', Hindi: 'इन्द्र', Telugu: 'ఇంద్రుడు', Kannada: 'ಇಂದ್ರ', Tamil: 'இந்திரன்', Malayalam: 'ഇന്ദ്രൻ' } },
  { id: '14', names: { English: 'Yama', Hindi: 'यम', Telugu: 'యముడు', Kannada: 'ಯಮ', Tamil: 'யமன்', Malayalam: 'യമൻ' } },
  { id: '15', names: { English: 'Aditya', Hindi: 'आदित्य', Telugu: 'ఆదిత్యుడు', Kannada: 'ಆದಿತ್ಯ', Tamil: 'ஆதித்யன்', Malayalam: 'ആദിത്യൻ' } },
  { id: '16', names: { English: 'Varuna (Water)', Hindi: 'वरुण', Telugu: 'వరుణుడు', Kannada: 'ವರುನ', Tamil: 'வருணன்', Malayalam: 'വർണൻ' } },
  { id: '17', names: { English: 'Shankara', Hindi: 'शंकर', Telugu: 'శంకరుడు', Kannada: 'ಶಂಕರ', Tamil: 'சங்கரன்', Malayalam: 'ശങ്കരൻ' } },
  { id: '18', names: { English: 'Mahadev', Hindi: 'महादेव', Telugu: 'మహాదేవుడు', Kannada: 'ಮಹಾದೇವ', Tamil: 'மகாதேவன்', Malayalam: 'മഹാദേവൻ' } },
  { id: '19', names: { English: 'Bhramha', Hindi: 'ब्रह्मा', Telugu: 'బ్రహ్మ', Kannada: 'ಬ್ರಹ್ಮ', Tamil: 'பிரம்மா', Malayalam: 'ബ്രഹ്മാവ്' } },
  { id: '20', names: { English: 'Kamadehnu', Hindi: 'कामधेनु', Telugu: 'కామధేనువు', Kannada: 'ಕಾಮಧೇನು', Tamil: 'காமதேனு', Malayalam: 'കാമധേനു' } },
  { id: '21', names: { English: 'Bhoomi', Hindi: 'भूमि', Telugu: 'భూమి', Kannada: 'ಭೂಮಿ', Tamil: 'பூமி', Malayalam: 'ഭൂമി' } },
  { id: '22', names: { English: 'Ganapati', Hindi: 'गणपति', Telugu: 'గణపతి', Kannada: 'ಗಣಪತಿ', Tamil: 'கணபதி', Malayalam: 'ഗണപതി' } },
  { id: '23', names: { English: 'Vigneshwara', Hindi: 'विघ्नेश्वर', Telugu: 'విఘ్నేశ్వరుడు', Kannada: 'ವಿಘ್ನೇಶ್ವರ', Tamil: 'விக்னேஸ்வரன்', Malayalam: 'വിഘ്നേശ്വരൻ' } },
  { id: '24', names: { English: 'Govinda', Hindi: 'गोविन्द', Telugu: 'గోవిందుడు', Kannada: 'ಗೋವಿಂದ', Tamil: 'கோவிந்தன்', Malayalam: 'ഗോവിന്ദൻ' } },
  { id: '25', names: { English: 'Narayana', Hindi: 'नारायण', Telugu: 'నారాయణుడు', Kannada: 'ನಾರಾಯಣ', Tamil: 'நாராயணன்', Malayalam: 'നാരായണൻ' } },
  { id: '26', names: { English: 'Venkatesha', Hindi: 'वेंकटेश', Telugu: 'వెంకటేశుడు', Kannada: 'ವೆಂಕಟೇಶ', Tamil: 'வெங்கடேசன்', Malayalam: 'വെങ്കടേശൻ' } },
  { id: '27', names: { English: 'Padmavathi', Hindi: 'पद्मावती', Telugu: 'పద్మావతి', Kannada: 'ಪದ್ಮಾವತಿ', Tamil: 'பத்மாவதி', Malayalam: 'പദ്മാവതി' } },
  { id: '29', names: { English: 'Dattatreya', Hindi: 'दत्तात्रेय', Telugu: 'దత్తాత్రేయుడు', Kannada: 'ದತ್ತಾತ್ರೇಯ', Tamil: 'தத்தாத்ரேயர்', Malayalam: 'ദത്താത്രേയൻ' } },
  { id: '30', names: { English: 'Kubera', Hindi: 'कुबेर', Telugu: 'కుబేరుడు', Kannada: 'ಕುವೇರ', Tamil: 'குபேரன்', Malayalam: 'കുബേരൻ' } },
  { id: '31', names: { English: 'Kaali', Hindi: 'काली', Telugu: 'కాళి', Kannada: 'ಕಾಳಿ', Tamil: 'காளி', Malayalam: 'കാളി' } },
  { id: '32', names: { English: 'Kala Bhairava', Hindi: 'काल भैरव', Telugu: 'కాల భైరవుడు', Kannada: 'ಕಾಲ ಭೈರವ', Tamil: 'கால பைரவன்', Malayalam: 'കാല ഭൈരവൻ' } },
  { id: '33', names: { English: 'Sita', Hindi: 'सीता', Telugu: 'సీత', Kannada: 'ಸೀತಾ', Tamil: 'சீதா', Malayalam: 'സീത' } },
  { id: '34', names: { English: 'Janaki', Hindi: 'जानकी', Telugu: 'జానకి', Kannada: 'ಜಾನಕಿ', Tamil: 'ஜானகி', Malayalam: 'ജാനകി' } },
  { id: '35', names: { English: 'Eshwara', Hindi: 'ईश्वर', Telugu: 'ఈశ్వరుడు', Kannada: 'ಈಶ್ವರ', Tamil: 'ஈஸ்வரன்', Malayalam: 'ഈശ്വരൻ' } },
  { id: '36', names: { English: 'Parvathi', Hindi: 'पार्वती', Telugu: 'పార్వతి', Kannada: 'ಪಾರ್ವತಿ', Tamil: 'பார்வதி', Malayalam: 'പാർവതി' } },
  { id: '37', names: { English: 'Surya', Hindi: 'सूर्य', Telugu: 'సూర్యుడు', Kannada: 'ಸೂರ್ಯ', Tamil: 'சூரியன்', Malayalam: 'സൂര്യൻ' } },
  { id: '38', names: { English: 'Gopala', Hindi: 'गोपाल', Telugu: 'గోపాలుడు', Kannada: 'ಗೋಪಾಲ', Tamil: 'கோபாலன்', Malayalam: 'ഗോപാലൻ' } },
  { id: '39', names: { English: 'Anjaneya', Hindi: 'अंजनेय', Telugu: 'అంజనేయుడు', Kannada: 'ಅಂಜನೇಯ', Tamil: 'அஞ்சனேயர்', Malayalam: 'അഞ്ജനേയൻ' } },
  { id: '40', names: { English: 'BalaRama', Hindi: 'बलराम', Telugu: 'బలరాముడు', Kannada: 'ಬಲರಾಮ', Tamil: 'பலராமன்', Malayalam: 'ബലരാമൻ' } },
  { id: '41', names: { English: 'Bharat', Hindi: 'भरत', Telugu: 'భరతుడు', Kannada: 'ಭರತ', Tamil: 'பாரத்', Malayalam: 'ഭാരത്' } },
  { id: '42', names: { English: 'Bharat Mata', Hindi: 'भारत माता', Telugu: 'భారత మాత', Kannada: 'ಭಾರತ ಮಾತೆ', Tamil: 'பாரத் மாதா', Malayalam: 'ഭാരത് മാതാ' } },
  { id: '43', names: { English: 'Garuda', Hindi: 'गरुड़', Telugu: 'గరుడుడు', Kannada: 'ಗರುಡ', Tamil: 'கருடன்', Malayalam: 'ഗരുഡൻ' } },
  { id: '44', names: { English: 'Gaja Laxmi', Hindi: 'गज लक्ष्मी', Telugu: 'గజ లక్ష్మి', Kannada: 'ಗಜ ಲಕ್ಷ್ಮೀ', Tamil: 'கஜலக்ஷ்மி', Malayalam: 'ഗജലക്ഷ്മി' } },
  { id: '45', names: { English: 'Santana Laxmi', Hindi: 'संतान लक्ष्मी', Telugu: 'సంతాన లక్ష్మి', Kannada: 'ಸಂತಾನ ಲಕ್ಷ್ಮೀ', Tamil: 'சந்தானலக்ஷ்மி', Malayalam: 'സന്താനലക്ഷ്മി' } },
  { id: '46', names: { English: 'Dhana Laxmi', Hindi: 'धन लक्ष्मी', Telugu: 'ధన లక్ష్మి', Kannada: 'ಧನ ಲಕ್ಷ್ಮೀ', Tamil: 'தனலக்ஷ்மி', Malayalam: 'ധനലക്ഷ്മി' } },
  { id: '47', names: { English: 'Dhanya Laxmi', Hindi: 'धान्य लक्ष्मी', Telugu: 'ధాన్య లక్ష్మి', Kannada: 'ಧಾನ್ಯ ಲಕ್ಷ್ಮೀ', Tamil: 'தான்யலக்ஷ்மி', Malayalam: 'ധാന്യലക്ഷ്മി' } },
  { id: '48', names: { English: 'Adi Lakshmi', Hindi: 'आदि लक्ष्मी', Telugu: 'ఆది లక్ష్మి', Kannada: 'ಆದಿ ಲಕ್ಷ್ಮೀ', Tamil: 'ஆதிலக்ஷ்மி', Malayalam: 'ആദിലക്ഷ്മി' } },
  { id: '49', names: { English: 'Dhairya Lakshmi', Hindi: 'धैर्य लक्ष्मी', Telugu: 'ధైర్య లక్ష్మి', Kannada: 'ಧೈರ್ಯ ಲಕ್ಷ್ಮೀ', Tamil: 'தைரியலக்ஷ்மி', Malayalam: 'ധൈര്യലക്ഷ്മി' } },
  { id: '50', names: { English: 'Vijaya Lakshmi', Hindi: 'विजया लक्ष्मी', Telugu: 'విజయ లక్ష్మి', Kannada: 'ವಿಜಯ ಲಕ್ಷ್ಮೀ', Tamil: 'விஜயலக்ஷ்மி', Malayalam: 'വിജയലക്ഷ്മി' } },
  { id: '51', names: { English: 'Vidya Lakshmi', Hindi: 'विद्यलक्ष्मी', Telugu: 'విద్యా లక్ష్మి', Kannada: 'ವಿದ್ಯಾ ಲಕ್ಷ್ಮಿ', Tamil: 'வித்யா லக்ஷ்மி', Malayalam: 'വിദ്യാ ലക്ഷ്മി' } },
  { id: '52', names: { English: 'Narashima', Hindi: 'नरसिम्हा', Telugu: 'నరసింహ', Kannada: 'ನರಸಿಂಹ', Tamil: 'நரசிம்மர்', Malayalam: 'നരസിംഹം' } },
  { id: '53', names: { English: 'Varaha', Hindi: 'वराह', Telugu: 'వరాహ', Kannada: 'ವರಾಹ', Tamil: 'வராகர்', Malayalam: 'വരാഹം' } },
  { id: '54', names: { English: 'Vamana', Hindi: 'वामन', Telugu: 'వామన', Kannada: 'ವಾಮನ', Tamil: 'வாமனர்', Malayalam: 'വാമനൻ' } },
  { id: '55', names: { English: 'Parashurama', Hindi: 'परशुराम', Telugu: 'పరశురామ', Kannada: 'ಪರಶುರಾಮ', Tamil: 'பரசுராமர்', Malayalam: 'പരശുരാമൻ' } },
  { id: '56', names: { English: 'Kalki', Hindi: 'कल्कि', Telugu: 'కల్కి', Kannada: 'ಕಲ್ಕಿ', Tamil: 'கல்கி', Malayalam: 'കൽക്കി' } },
  { id: '57', names: { English: 'Koorma', Hindi: 'कुर्मः', Telugu: 'కూర్మ', Kannada: 'ಕೂರ್ಮ', Tamil: 'கூர்மர்', Malayalam: 'കൂർമ്മം' } },
  { id: '58', names: { English: 'Matsya', Hindi: 'मात्स्य', Telugu: 'మత్స్య', Kannada: 'ಮತ್ಸ್ಯ', Tamil: 'மத்ஸ்ய (மச்ச அவதாரம்)', Malayalam: 'മത്സ്യം' } },
  { id: '59', names: { English: 'Mohini', Hindi: 'मोहिनी', Telugu: 'మోహిని', Kannada: 'ಮೋಹಿನಿ', Tamil: 'மோகினி', Malayalam: 'മോഹിനി' } },
  { id: '60', names: { English: 'Muruga', Hindi: 'भगवान मुरुगन', Telugu: 'మురుగ', Kannada: 'ಮುರುಗ', Tamil: 'முருகன்', Malayalam: 'മുരുകൻ' } },
  { id: '61', names: { English: 'Shakti Amma', Hindi: 'शक्ति अम्मा', Telugu: 'శక్తి అమ్మ', Kannada: 'ಶಕ್ತಿ ಅಮ್ಮ', Tamil: 'சக்தி அம்மா', Malayalam: 'ശക്തി അമ്മ' } },
  { id: '62', names: { English: 'Radha', Hindi: 'राधा', Telugu: 'రాధ', Kannada: 'ರಾಧಾ', Tamil: 'ராதா', Malayalam: 'രാധ' } },
  { id: '63', names: { English: 'Varahi', Hindi: 'वाराही', Telugu: 'వరాహి', Kannada: 'ವಾರಾಹಿ', Tamil: 'வராஹி', Malayalam: 'വരാഹി' } },
  { id: '64', names: { English: 'Chandra', Hindi: 'चन्द्र', Telugu: 'చంద్రుడు', Kannada: 'ಚಂದ್ರ', Tamil: 'சந்திரன்', Malayalam: 'ചന്ദ്രൻ' } },
  { id: '65', names: { English: 'Shukra', Hindi: 'शुक्र', Telugu: 'శుక్రుడు', Kannada: 'ಶುಕ್ರ', Tamil: 'சுக்ரன்', Malayalam: 'ശുക്രൻ' } },
  { id: '66', names: { English: 'Shani', Hindi: 'शनि', Telugu: 'శని', Kannada: 'ಶನಿ', Tamil: 'சனி', Malayalam: 'ശനി' } },
  { id: '67', names: { English: 'Rahu', Hindi: 'राहु', Telugu: 'రాహు', Kannada: 'ರಾಹು', Tamil: 'ராகு', Malayalam: 'രാഹു' } },
  { id: '68', names: { English: 'Ketu', Hindi: 'केतु', Telugu: 'కేతు', Kannada: 'ಕೇತು', Tamil: 'கேது', Malayalam: 'കേതു' } },
  { id: '69', names: { English: 'Pashupathi', Hindi: 'पशुपति', Telugu: 'పశుపతి', Kannada: 'ಪಶುಪತಿ', Tamil: 'பசுபதி', Malayalam: 'പശുപതി' } },
  { id: '70', names: { English: 'Venu Gopala', Hindi: 'वेनु गोपाल', Telugu: 'వేణు గోపాలుడు', Kannada: 'ವೇಣು ಗೋಪಾಲ', Tamil: 'வேணு கோபாலன்', Malayalam: 'വേണു ഗോപാലൻ' } },
  { id: '71', names: { English: 'Vasudha', Hindi: 'वसुधा', Telugu: 'వసుధా', Kannada: 'ವಸುಧಾ', Tamil: 'வசுதா', Malayalam: 'വസുധ' } },
  { id: '72', names: { English: 'Narada', Hindi: 'नारद', Telugu: 'నారదుడు', Kannada: 'ನಾರದ', Tamil: 'நாரதர்', Malayalam: 'നാരദൻ' } },
  { id: '73', names: { English: 'Nandhi', Hindi: 'नंदी', Telugu: 'నంది', Kannada: 'ನಂದಿ', Tamil: 'நந்தி', Malayalam: 'നന്ദി' } },
  { id: '74', names: { English: 'Mooshika', Hindi: 'मूषक', Telugu: 'మూషిక', Kannada: 'ಮೂಷಿಕ', Tamil: 'மூஷிகன்', Malayalam: 'മൂഷികൻ' } },
  { id: '75', names: { English: 'Guru Bhruhaspati', Hindi: 'गुरु बृहस्पति', Telugu: 'గురు బృహస్పతి', Kannada: 'ಗುರು ಬೃಹಸ್ಪತಿ', Tamil: 'குரு ப்ருஹஸ்பதி', Malayalam: 'ഗുരു ബൃഹസ്പതി' } },
  { id: '76', names: { English: 'Mangala', Hindi: 'मंगल', Telugu: 'మంగళుడు', Kannada: 'ಮಂಗಳ', Tamil: 'மங்களன்', Malayalam: 'മംഗളൻ' } },
  { id: '77', names: { English: 'Bhudha', Hindi: 'बुध', Telugu: 'బుధుడు', Kannada: 'ಬುಧ', Tamil: 'புதன்', Malayalam: 'ബുധൻ' } },
  { id: '78', names: { English: 'Soma', Hindi: 'सोम', Telugu: 'సోముడు', Kannada: 'ಸೋಮ', Tamil: 'சோமன்', Malayalam: 'സോമൻ' } },
  { id: '79', names: { English: 'Skanda', Hindi: 'स्कंद', Telugu: 'స్కందుడు', Kannada: 'ಸ್ಕಂದ', Tamil: 'ஸ்கந்தன்', Malayalam: 'സ്കന്ദൻ' } },
  { id: '80', names: { English: 'Vasukhi', Hindi: 'वासुकी', Telugu: 'వాసుకి', Kannada: 'ವಾಸುಕಿ', Tamil: 'வாசுகி', Malayalam: 'വാസുകി' } },
  { id: '81', names: { English: 'Anantha', Hindi: 'अनंत', Telugu: 'అనంతుడు', Kannada: 'ಅನಂತ', Tamil: 'அனந்தன்', Malayalam: 'അനന്തൻ' } },
  { id: '82', names: { English: 'Shailaputri', Hindi: 'शैलपुत्री', Telugu: 'శైలపుత్రి', Kannada: 'ಶೈಲಪುತ್ರಿ', Tamil: 'சைலபுத்ரி', Malayalam: 'ശൈലപുത്രി' } },
  { id: '83', names: { English: 'Brahmacharini', Hindi: 'ब्रह्मचारिणी', Telugu: 'బ్రహ్మచారిణి', Kannada: 'ಬ್ರಹ್ಮಚಾರಿಣಿ', Tamil: 'பிரம்மசாரிணி', Malayalam: 'ബ്രഹ്മചാരിണി' } },
  { id: '84', names: { English: 'Chandraganta', Hindi: 'चंद्रघंटा', Telugu: 'చంద్రగంట', Kannada: 'ಚಂದ್ರಘಂಟಾ', Tamil: 'சந்திரகண்டா', Malayalam: 'ചന്ദ്രഗണ്ടാ' } },
  { id: '85', names: { English: 'Kushmanda', Hindi: 'कुष्मांडा', Telugu: 'కుష్మాండ', Kannada: 'ಕುಷ್ಮಾಂಡಾ', Tamil: 'குஷ்மாண்டா', Malayalam: 'കുഷ്മാണ്ടാ' } },
  { id: '86', names: { English: 'Skandamata', Hindi: 'स्कंदमाता', Telugu: 'స్కందమాత', Kannada: 'ಸ್ಕಂದಮಾತಾ', Tamil: 'ஸ்கந்தமாதா', Malayalam: 'സ്കന്ദമാതാ' } },
  { id: '87', names: { English: 'Katyayani', Hindi: 'कात्यायनी', Telugu: 'కాత్యాయనీ', Kannada: 'ಕಾತ್ಯಾಯನಿ', Tamil: 'காத்யாயனி', Malayalam: 'കാത്യായനി' } },
  { id: '88', names: { English: 'Kalaratri', Hindi: 'कालरात्रि', Telugu: 'కాలరాత్రి', Kannada: 'ಕಾಲರಾತ್ರಿ', Tamil: 'காலராத்திரி', Malayalam: 'കാലരാത്രി' } },
  { id: '89', names: { English: 'Mahagauri', Hindi: 'महागौरी', Telugu: 'మహాగౌరి', Kannada: 'ಮಹಾಗೌರಿ', Tamil: 'மஹாகௌரி', Malayalam: 'മഹാഗൗരി' } },
  { id: '90', names: { English: 'Siddhidhatri', Hindi: 'सिद्धिदात्री', Telugu: 'సిద్ధిధాత్రి', Kannada: 'ಸಿದ್ಧಿಧಾತ್ರೀ', Tamil: 'சித்திதாத்ரி', Malayalam: 'സിദ്ധിധാത്രി' } },
  { id: '91', names: { English: 'Hayagriva', Hindi: 'हयग्रीव', Telugu: 'హయగ్రీవుడు', Kannada: 'ಹಯಗ್ರೀವ', Tamil: 'ஹயக்ரீவர்', Malayalam: 'ഹയഗ്രീവൻ' } },
  { id: '92', names: { English: 'Nataraja', Hindi: 'नटराज', Telugu: 'నటరాజు', Kannada: 'ನಟರಾಜ', Tamil: 'நடராஜர்', Malayalam: 'നടരാജൻ' } },
  { id: '93', names: { English: 'KanyaKumari', Hindi: 'कन्याकुमारी', Telugu: 'కన్యాకుమారి', Kannada: 'ಕನ್ಯಾಕುಮಾರಿ', Tamil: 'கன்னியாகுமரி', Malayalam: 'കന്ന്യാകുമാരി' } },
  { id: '94', names: { English: 'Buddha', Hindi: 'बुद्ध', Telugu: 'బుద్ధుడు', Kannada: 'ಬುದ್ಧ', Tamil: 'புத்தர்', Malayalam: 'ബുദ്ധൻ' } },
  { id: '95', names: { English: 'Kamakshi', Hindi: 'कामाक्षी', Telugu: 'కామాక్షి', Kannada: 'ಕಾಮಾಕ್ಷಿ', Tamil: 'காமாட்சி', Malayalam: 'കാമാക്ഷി' } },
  { id: '96', names: { English: 'Bhavani', Hindi: 'भवानी', Telugu: 'భవాని', Kannada: 'ಭವಾನಿ', Tamil: 'பவானி', Malayalam: 'ಭವാനി' } },
  { id: '97', names: { English: 'Chandra Maulishwara', Hindi: 'चन्द्र मौलीश्वर', Telugu: 'చంద్ర మౌలీశ్వరుడు', Kannada: 'ಚಂದ್ರಮೌಲೀಶ್ವರ', Tamil: 'சந்திரமௌலீஸ்வரர்', Malayalam: 'ചന്ദ്രമൗലീശ്വരൻ' } },
  { id: '98', names: { English: 'Linga', Hindi: 'लिंग', Telugu: 'లింగం', Kannada: 'ಲಿಂಗ', Tamil: 'லிங்கம்', Malayalam: 'ലിംഗം' } },
  { id: '99', names: { English: 'Timmappa', Hindi: 'तिम्मप्पा', Telugu: 'తిమ్మప్ప', Kannada: 'ತಿಮ್ಮಪ್ಪ', Tamil: 'திம்மப்பா', Malayalam: 'തിമ്മപ്പ' } },
  { id: '100', names: { English: 'Balaji', Hindi: 'बालाजी', Telugu: 'బాలాజీ', Kannada: 'ಬಾಲಾಜಿ', Tamil: 'பாலாஜி', Malayalam: 'ബാലാജി' } },
  { id: '101', names: { English: 'Rajalaxmi', Hindi: 'राजलक्ष्मी', Telugu: 'రాజలక్ష్మి', Kannada: 'ರಾಜಲಕ್ಷ್ಮೀ', Tamil: 'ராஜலக்ஷ்மி', Malayalam: 'രാജലക്ഷ്മി' } },
  { id: '102', names: { English: 'Sharadha', Hindi: 'शारदा', Telugu: 'శారద', Kannada: 'ಶಾರದಾ', Tamil: 'சாரதா', Malayalam: 'शारदा' } },
  { id: '103', names: { English: 'Parameshwari', Hindi: 'परमेश्वरी', Telugu: 'పరమేశ్వరి', Kannada: 'ಪರಮೇಶ್ವರಿ', Tamil: 'பரமேஸ்வரி', Malayalam: 'പരമേശ്വരി' } },
  { id: '104', names: { English: 'Hari', Hindi: 'हरि', Telugu: 'హరి', Kannada: 'ಹರಿ', Tamil: 'ஹரி', Malayalam: 'ഹരി' } },
  { id: '106', names: { English: 'Bhola', Hindi: 'भोला', Telugu: 'భోలా', Kannada: 'ಭೋಲಾ', Tamil: 'போலா', Malayalam: 'ഭോളാ' } },
  { id: '107', names: { English: 'Ayyappa', Hindi: 'अय्यप्पा', Telugu: 'అయ్యప్ప', Kannada: 'ಅಯ್ಯಪ್ಪ', Tamil: 'அய்யப்பன்', Malayalam: 'അയ്യപ്പൻ' } },
  { id: '108', names: { English: 'Manikanta', Hindi: 'मणिकांत', Telugu: 'మణికాంత', Kannada: 'ಮಣಿಕಾಂತ', Tamil: 'மணிகண்டன்', Malayalam: 'മണികണ്ഠൻ' } },
  { id: '109', names: { English: 'Parameshwara', Hindi: 'परमेश्वर', Telugu: 'పరమేశ్వరుడు', Kannada: 'ಪರಮೇಶ್ವರ', Tamil: 'பரமேஸ்வரன்', Malayalam: 'പരമേശ്വരൻ' } },
  { id: '110', names: { English: 'Shivani', Hindi: 'शिवानी', Telugu: 'శివాని', Kannada: 'ಶಿವಾನಿ', Tamil: 'சிவானி', Malayalam: 'ശിവാനി' } },
  { id: '111', names: { English: 'Sastha', Hindi: 'शास्ता', Telugu: 'శాస్తా', Kannada: 'ಶಾಸ್ತಾ', Tamil: 'சாஸ்தா', Malayalam: 'ശാസ്താ' } },
  { id: '112', names: { English: 'Gajanan', Hindi: 'गजानन', Telugu: 'గజాననుడు', Kannada: 'ಗಜಾನನ', Tamil: 'கஜானன்', Malayalam: 'ഗജാനൻ' } },
  { id: '113', names: { English: 'Srinivasa', Hindi: 'श्रीनिवास', Telugu: 'శ్రీనివాస', Kannada: 'ಶ್ರೀನಿವಾಸ', Tamil: 'ஸ்ரீனிவாசன்', Malayalam: 'ശ്രീനിവാസൻ' } },
  { id: '114', names: { English: 'Maruti', Hindi: 'मारुति', Telugu: 'మారుతి', Kannada: 'ಮಾರುತಿ', Tamil: 'மாருதி', Malayalam: 'മാരുതി' } },
  { id: '117', names: { English: 'Vittala', Hindi: 'विट्ठल', Telugu: 'విఠల', Kannada: 'ವಿಠಲ', Tamil: 'விட்டலா', Malayalam: 'വിഠല' } },
  { id: '118', names: { English: 'Jaganatha', Hindi: 'जगन्नाथ', Telugu: 'జగన్నాథ', Kannada: 'ಜಗನ್ನಾಥ', Tamil: 'ஜகன்னாதர்', Malayalam: 'ജഗന്നാഥൻ' } },
  { id: '119', names: { English: 'Sadashiva', Hindi: 'सदाशिव', Telugu: 'సదాశివ', Kannada: 'ಸದಾಶಿವ', Tamil: 'சதாசிவன்', Malayalam: 'സദാശിവൻ' } },
  { id: '120', names: { English: 'Govardhana', Hindi: 'गोवर्धन', Telugu: 'గోవర్ధన', Kannada: 'ಗೋವರ್ಧನ', Tamil: 'கோவர்த்தனா', Malayalam: 'ഗോവർദ്ധന' } }
];

export const INITIAL_CHAT_MESSAGE = "Namaste! I am your guide to Hindu mythology. Ask me anything about the gods, their stories, or the quiz images.";

interface DifficultyConfig {
  options: number;
  points: number;
  label: string;
  rounds: number;
}

export const DIFFICULTY_SETTINGS: Record<Difficulty, DifficultyConfig> = {
  easy: { options: 2, points: 10, label: "Easy", rounds: 5 },
  medium: { options: 4, points: 20, label: "Medium", rounds: 10 },
  hard: { options: 4, points: 30, label: "Hard", rounds: 15 }
};
