
import { God, Difficulty } from './types';

// Data parsed from the provided CSV file
export const HINDU_GODS: God[] = [
  { id: '1', names: { English: 'Shiva', Hindi: 'शिव', Telugu: 'శివుడు', Kannada: 'ಶಿವ', Tamil: 'சிவன்', Malayalam: 'ശിവൻ' }, mantra: 'Om Namah Shivaya' },
  { id: '2', names: { English: 'Vishnu', Hindi: 'विष्णु', Telugu: 'విష్ణువు', Kannada: 'ವಿಷ್ಣು', Tamil: 'விஷ்ணு', Malayalam: 'വിഷ്ണു' }, mantra: 'Om Vishnave Namaha' },
  { id: '3', names: { English: 'Lakshmi', Hindi: 'लक्ष्मी', Telugu: 'లక్ష్మి', Kannada: 'ಲಕ್ಷ್ಮೀ', Tamil: 'லட்சுமி', Malayalam: 'ലക്ഷ്മി' }, mantra: 'Om Lakshmiye Namaha' },
  { id: '4', names: { English: 'Saraswati', Hindi: 'सरस्वती', Telugu: 'సరస్వతి', Kannada: 'ಸರಸ್ವತಿ', Tamil: 'சரஸ்வதி', Malayalam: 'സരസ്വതി' }, mantra: 'Om Saraswati Namaha' },
  { id: '5', names: { English: 'Krishna', Hindi: 'कृष्ण', Telugu: 'కృష్ణుడు', Kannada: 'ಕೃಷ್ಣ', Tamil: 'கிருஷ்ணன்', Malayalam: 'കൃഷ്ണൻ' }, mantra: 'Om Krishave Namaha' },
  { id: '6', names: { English: 'Rama', Hindi: 'राम', Telugu: 'రాముడు', Kannada: 'ರಾಮ', Tamil: 'ராமன்', Malayalam: 'രാമൻ' }, mantra: 'Om Ramaya Namaha' },
  { id: '7', names: { English: 'Hanuman', Hindi: 'हनुमान', Telugu: 'హనుమంతుడు', Kannada: 'ಹನುಮಾನ್', Tamil: 'ஹனுமான்', Malayalam: 'ഹനുമാൻ' }, mantra: 'Om Hanumava Namha' },
  { id: '8', names: { English: 'Ganesha', Hindi: 'गणेश', Telugu: 'గణేశుడు', Kannada: 'ಗಣೇಶ', Tamil: 'விநாயகர்', Malayalam: 'ഗണേശൻ' }, mantra: 'Om Ganeshaya Namaha' },
  { id: '9', names: { English: 'Durga', Hindi: 'दुर्गा', Telugu: 'దుర్గ', Kannada: 'ದುರ್ಗಾ', Tamil: 'துர்கா', Malayalam: 'ദുർഗ്ഗ' }, mantra: 'Om Durgaya Namaha' },
  { id: '10', names: { English: 'Kartikeya', Hindi: 'कार्तिकेय', Telugu: 'కార్తికేయ', Kannada: 'ಕಾರ್ತಿಕೇಯ', Tamil: 'கார்த்திகேயன்', Malayalam: 'കാർത്തികേയൻ' }, mantra: 'Om Kartikaya Namaha' },
  { id: '11', names: { English: 'Agni (Fire)', Hindi: 'अग्नि', Telugu: 'అగ్ని', Kannada: 'ಅಗ್ನಿ', Tamil: 'அக்னி', Malayalam: 'അഗ്നി' }, mantra: 'Om Agnave Namaha' },
  { id: '12', names: { English: 'Vayu (Wind)', Hindi: 'वायु', Telugu: 'వాయువు', Kannada: 'ವಾಯು', Tamil: 'வாயு', Malayalam: 'വായു' }, mantra: 'Om Vayuve Namaha' },
  { id: '13', names: { English: 'Indra', Hindi: 'इन्द्र', Telugu: 'ఇంద్రుడు', Kannada: 'ಇಂದ್ರ', Tamil: 'இந்திரன்', Malayalam: 'ഇന്ദ്രൻ' }, mantra: 'Om Indraya Namaha' },
  { id: '14', names: { English: 'Yama', Hindi: 'यम', Telugu: 'యముడు', Kannada: 'ಯಮ', Tamil: 'யமன்', Malayalam: 'യമൻ' }, mantra: 'Om Yamaye Namaha' },
  { id: '15', names: { English: 'Aditya', Hindi: 'आदित्य', Telugu: 'ఆదిత్యుడు', Kannada: 'ಆದಿತ್ಯ', Tamil: 'ஆதித்யன்', Malayalam: 'ആദിത്യൻ' }, mantra: 'Om Adityaya Namaha' },
  { id: '16', names: { English: 'Varuna (Water)', Hindi: 'वरुण', Telugu: 'వరుణుడు', Kannada: 'ವರುನ', Tamil: 'வருணன்', Malayalam: 'വർണൻ' }, mantra: 'Om Varunave Namaha' },
  { id: '17', names: { English: 'Shankara', Hindi: 'शंकर', Telugu: 'శంకరుడు', Kannada: 'ಶಂಕರ', Tamil: 'சங்கரன்', Malayalam: 'ശങ്കരൻ' }, mantra: 'Om Shankaraya Namaha' },
  { id: '18', names: { English: 'Mahadev', Hindi: 'महादेव', Telugu: 'మహాదేవుడు', Kannada: 'ಮಹಾದೇವ', Tamil: 'மகாதேவன்', Malayalam: 'മഹാദേവൻ' }, mantra: 'Om Mahadevaya Namaha' },
  { id: '19', names: { English: 'Bhramha', Hindi: 'ब्रह्मा', Telugu: 'బ్రహ్మ', Kannada: 'ಬ್ರಹ್ಮ', Tamil: 'பிரம்மா', Malayalam: 'ബ്രഹ്മാവ്' }, mantra: 'Om Bhramhaya Namaha' },
  { id: '20', names: { English: 'Kamadehnu', Hindi: 'कामधेनु', Telugu: 'కామధేనువు', Kannada: 'ಕಾಮಧೇನು', Tamil: 'காமதேனு', Malayalam: 'കാമധേനു' }, mantra: 'Om Kamadehnave Namaha' },
  { id: '21', names: { English: 'Bhoomi', Hindi: 'भूमि', Telugu: 'భూమి', Kannada: 'ಭೂಮಿ', Tamil: 'பூமி', Malayalam: 'ഭൂമി' }, mantra: 'Om Bhoomiye Namaha' },
  { id: '22', names: { English: 'Ganapati', Hindi: 'गणपति', Telugu: 'గణపతి', Kannada: 'ಗಣಪತಿ', Tamil: 'கணபதி', Malayalam: 'ഗണപതി' }, mantra: 'Om Ganapatiye Namaha' },
  { id: '23', names: { English: 'Vigneshwara', Hindi: 'विघ्नेश्वर', Telugu: 'విఘ్నేశ్వరుడు', Kannada: 'ವಿಘ್ನೇಶ್ವರ', Tamil: 'விக்னேஸ்வரன்', Malayalam: 'വിഘ്നേശ്വരൻ' }, mantra: 'Om Vigneshwaraya Namaha' },
  { id: '24', names: { English: 'Govinda', Hindi: 'गोविन्द', Telugu: 'గోవిందుడు', Kannada: 'ಗೋವಿಂದ', Tamil: 'கோவிந்தன்', Malayalam: 'ഗോവിന്ദൻ' }, mantra: 'Om Govindaya Namaha' },
  { id: '25', names: { English: 'Narayana', Hindi: 'नारायण', Telugu: 'నారాయణుడు', Kannada: 'ನಾರಾಯಣ', Tamil: 'நாராயணன்', Malayalam: 'നാരായണൻ' }, mantra: 'Om Narayana Namaha' },
  { id: '26', names: { English: 'Venkatesha', Hindi: 'वेंकटेश', Telugu: 'వెంకటేశుడు', Kannada: 'ವೆಂಕಟೇಶ', Tamil: 'வெங்கடேசன்', Malayalam: 'വെങ്കടേശൻ' }, mantra: 'Om Venkateshaya Namaha' },
  { id: '27', names: { English: 'Padmavathi', Hindi: 'पद्मावती', Telugu: 'పద్మావతి', Kannada: 'ಪದ್ಮಾವತಿ', Tamil: 'பத்மாவதி', Malayalam: 'പദ്മാവതി' }, mantra: 'Om Padmavathiye Namaha' },
  { id: '29', names: { English: 'Dattatreya', Hindi: 'दत्तात्रेय', Telugu: 'దత్తాత్రేయుడు', Kannada: 'ದತ್ತಾತ್ರೇಯ', Tamil: 'தத்தாத்ரேயர்', Malayalam: 'ദത്താത്രേയൻ' }, mantra: 'Om Dattatreyaye Namaha' },
  { id: '30', names: { English: 'Kubera', Hindi: 'कुबेर', Telugu: 'కుబేరుడు', Kannada: 'ಕುವೇರ', Tamil: 'குபேரன்', Malayalam: 'കുബേരൻ' }, mantra: 'Om Kuberaya Namaha' },
  { id: '31', names: { English: 'Kaali', Hindi: 'काली', Telugu: 'కాళి', Kannada: 'ಕಾಳಿ', Tamil: 'காளி', Malayalam: 'കാളി' }, mantra: 'Om Kaaliye Namaha' },
  { id: '32', names: { English: 'Kala Bhairava', Hindi: 'काल भैरव', Telugu: 'కాల భైరవుడు', Kannada: 'ಕಾಲ ಭೈರವ', Tamil: 'கால பைரவன்', Malayalam: 'കാല ഭൈരവൻ' }, mantra: 'Om Kala Bhairavayya Namaha' },
  { id: '33', names: { English: 'Sita', Hindi: 'सीता', Telugu: 'సీత', Kannada: 'ಸೀತಾ', Tamil: 'சீதா', Malayalam: 'സീത' }, mantra: 'Om Sitaaiiye Namaha' },
  { id: '34', names: { English: 'Janaki', Hindi: 'जानकी', Telugu: 'జానకి', Kannada: 'ಜಾನಕಿ', Tamil: 'ஜானகி', Malayalam: 'ജാനകി' }, mantra: 'Om Janakiaiye Namaha' },
  { id: '35', names: { English: 'Eshwara', Hindi: 'ईश्वर', Telugu: 'ఈశ్వరుడు', Kannada: 'ಈಶ್ವರ', Tamil: 'ஈஸ்வரன்', Malayalam: 'ഈശ്വരൻ' }, mantra: 'Om Eshwaraiye Namaha' },
  { id: '36', names: { English: 'Parvathi', Hindi: 'पार्वती', Telugu: 'పార్వతి', Kannada: 'ಪಾರ್ವತಿ', Tamil: 'பார்வதி', Malayalam: 'പാർവതി' }, mantra: 'Om Parvathiaiye Namaha' },
  { id: '37', names: { English: 'Surya', Hindi: 'सूर्य', Telugu: 'సూర్యుడు', Kannada: 'ಸೂರ್ಯ', Tamil: 'சூரியன்', Malayalam: 'സൂര്യൻ' }, mantra: 'Om Suryaiye Namaha' },
  { id: '38', names: { English: 'Gopala', Hindi: 'गोपाल', Telugu: 'గోపాలుడు', Kannada: 'ಗೋಪಾಲ', Tamil: 'கோபாலன்', Malayalam: 'ഗോപാലൻ' }, mantra: 'Om Gopala Govinda' },
  { id: '39', names: { English: 'Anjaneya', Hindi: 'अंजनेय', Telugu: 'అంజనేయుడు', Kannada: 'ಅಂಜನೇಯ', Tamil: 'அஞ்சனேயர்', Malayalam: 'അഞ്ജനേയൻ' }, mantra: 'Om Anjaneyaye Namaha' },
  { id: '40', names: { English: 'BalaRama', Hindi: 'बलराम', Telugu: 'బలరాముడు', Kannada: 'ಬಲರಾಮ', Tamil: 'பலராமன்', Malayalam: 'ബലരാമൻ' }, mantra: 'Om BalaRamaaiye Namaha' },
  { id: '41', names: { English: 'Bharat', Hindi: 'भरत', Telugu: 'భరతుడు', Kannada: 'ಭರತ', Tamil: 'பாரத்', Malayalam: 'ഭാരത്' }, mantra: 'Om Bharataiye Namaha' },
  { id: '42', names: { English: 'Bharat Mata', Hindi: 'भारत माता', Telugu: 'భారత మాత', Kannada: 'ಭಾರತ ಮಾತೆ', Tamil: 'பாரத் மாதா', Malayalam: 'ഭാരത് മാതാ' }, mantra: 'Bharat Mata Ki Jai' },
  { id: '43', names: { English: 'Garuda', Hindi: 'गरुड़', Telugu: 'గరుడుడు', Kannada: 'ಗರುಡ', Tamil: 'கருடன்', Malayalam: 'ഗരുഡൻ' }, mantra: 'Om Garudaiye Namaha' },
  { id: '44', names: { English: 'Gaja Laxmi', Hindi: 'गज लक्ष्मी', Telugu: 'గజ లక్ష్మి', Kannada: 'ಗಜ ಲಕ್ಷ್ಮೀ', Tamil: 'கஜலக்ஷ்மி', Malayalam: 'ഗജലക്ഷ്മി' }, mantra: 'Om Gaja Laxmiye Namaha' },
  { id: '45', names: { English: 'Santana Laxmi', Hindi: 'संतान लक्ष्मी', Telugu: 'సంతాన లక్ష్మి', Kannada: 'ಸಂತಾನ ಲಕ್ಷ್ಮೀ', Tamil: 'சந்தானலக்ஷ்மி', Malayalam: 'സന്താനലക്ഷ്മി' }, mantra: 'Om Santana Laxmiye Namaha' },
  { id: '46', names: { English: 'Dhana Laxmi', Hindi: 'धन लक्ष्मी', Telugu: 'ధన లక్ష్మి', Kannada: 'ಧನ ಲಕ್ಷ್ಮೀ', Tamil: 'தனலக்ஷ்மி', Malayalam: 'ധനലക്ഷ്മി' }, mantra: 'Om Dhana Laxmiaiye Namaha' },
  { id: '47', names: { English: 'Dhanya Laxmi', Hindi: 'धान्य लक्ष्मी', Telugu: 'ధాన్య లక్ష్మి', Kannada: 'ಧಾನ್ಯ ಲಕ್ಷ್ಮೀ', Tamil: 'தான்யலக்ஷ்மி', Malayalam: 'ധാന്യലക്ഷ്മി' }, mantra: 'Om Dhanya Laxmiaiye Namaha' },
  { id: '48', names: { English: 'Adi Lakshmi', Hindi: 'आदि लक्ष्मी', Telugu: 'ఆది లక్ష్మి', Kannada: 'ಆದಿ ಲಕ್ಷ್ಮೀ', Tamil: 'ஆதிலக்ஷ்மி', Malayalam: 'ആദിലക്ഷ്മി' }, mantra: 'Om Adi Lakshmiaiye Namaha' },
  { id: '49', names: { English: 'Dhairya Lakshmi', Hindi: 'धैर्य लक्ष्मी', Telugu: 'ధైర్య లక్ష్మి', Kannada: 'ಧೈರ್ಯ ಲಕ್ಷ್ಮೀ', Tamil: 'தைரியலக்ஷ்மி', Malayalam: 'ധൈര്യലക്ഷ്മി' }, mantra: 'Om Dhairya Lakshmiaiye Namaha' },
  { id: '50', names: { English: 'Vijaya Lakshmi', Hindi: 'विजया लक्ष्मी', Telugu: 'విజయ లక్ష్మి', Kannada: 'ವಿಜಯ ಲಕ್ಷ್ಮೀ', Tamil: 'விஜயலக்ஷ்மி', Malayalam: 'വിജയലക്ഷ്മി' }, mantra: 'Om Vijaya Lakshmiaiye Namaha' },
  { id: '51', names: { English: 'Vidya Lakshmi', Hindi: 'विद्यलक्ष्मी', Telugu: 'విద్యా లక్ష్మి', Kannada: 'ವಿದ್ಯಾ ಲಕ್ಷ್ಮಿ', Tamil: 'வித்யா லக்ஷ்மி', Malayalam: 'വിദ്യാ ലക്ഷ്മി' }, mantra: 'Om Vidya Lakshmiaiye Namaha' },
  { id: '52', names: { English: 'Narashima', Hindi: 'नरसिम्हा', Telugu: 'నరసింహ', Kannada: 'ನರಸಿಂಹ', Tamil: 'நரசிம்மர்', Malayalam: 'നരസിംഹം' }, mantra: 'Ugra Narashima Lakshmi Narashima' },
  { id: '53', names: { English: 'Varaha', Hindi: 'वराह', Telugu: 'వరాహ', Kannada: 'ವರಾಹ', Tamil: 'வராகர்', Malayalam: 'വരാഹം' }, mantra: 'Om Varahaiye Namaha' },
  { id: '54', names: { English: 'Vamana', Hindi: 'वामन', Telugu: 'వామన', Kannada: 'ವಾಮನ', Tamil: 'வாமனர்', Malayalam: 'വാമനൻ' }, mantra: 'Om Vamanaiye Namaha' },
  { id: '55', names: { English: 'Parashurama', Hindi: 'परशुराम', Telugu: 'పరశురామ', Kannada: 'ಪರಶುರಾಮ', Tamil: 'பரசுராமர்', Malayalam: 'പരശുരാമൻ' }, mantra: 'Om Parashuramaiye Namaha' },
  { id: '56', names: { English: 'Kalki', Hindi: 'कल्कि', Telugu: 'కల్కి', Kannada: 'ಕಲ್ಕಿ', Tamil: 'கல்கி', Malayalam: 'കൽക്കി' }, mantra: 'Om Kalkiiye Namaha' },
  { id: '57', names: { English: 'Koorma', Hindi: 'कुर्मः', Telugu: 'కూర్మ', Kannada: 'ಕೂರ್ಮ', Tamil: 'கூர்மர்', Malayalam: 'കൂർമ്മം' }, mantra: 'Om Koormaiye Namaha' },
  { id: '58', names: { English: 'Matsya', Hindi: 'मात्स्य', Telugu: 'మత్స్య', Kannada: 'ಮತ್ಸ್ಯ', Tamil: 'மத்ஸ்ய (மச்ச அவதாரம்)', Malayalam: 'മത്സ്യം' }, mantra: 'Om Matsyaiye Namaha' },
  { id: '59', names: { English: 'Mohini', Hindi: 'मोहिनी', Telugu: 'మోహిని', Kannada: 'ಮೋಹಿನಿ', Tamil: 'மோகினி', Malayalam: 'മോഹിനി' }, mantra: 'Om Mohiniiye Namaha' },
  { id: '60', names: { English: 'Muruga', Hindi: 'भगवान मुरुगन', Telugu: 'మురుగ', Kannada: 'ಮುರುಗ', Tamil: 'முருகன்', Malayalam: 'മുരുകൻ' }, mantra: 'Murga Muruga' },
  { id: '61', names: { English: 'Shakti Amma', Hindi: 'शक्ति अम्मा', Telugu: 'శక్తి అమ్మ', Kannada: 'ಶಕ್ತಿ ಅಮ್ಮ', Tamil: 'சக்தி அம்மா', Malayalam: 'ശക്തി അമ്മ' }, mantra: 'Om Shakti Ammaaiye Namaha' },
  { id: '62', names: { English: 'Radha', Hindi: 'राधा', Telugu: 'రాధ', Kannada: 'ರಾಧಾ', Tamil: 'ராதா', Malayalam: 'രാധ' }, mantra: 'Radhe Radhe' },
  { id: '63', names: { English: 'Varahi', Hindi: 'वाराही', Telugu: 'వరాహి', Kannada: 'ವಾರಾಹಿ', Tamil: 'வராஹி', Malayalam: 'വരാഹി' }, mantra: 'Om Varahiiye Namaha' },
  { id: '64', names: { English: 'Chandra', Hindi: 'चन्द्र', Telugu: 'చంద్రుడు', Kannada: 'ಚಂದ್ರ', Tamil: 'சந்திரன்', Malayalam: 'ചന്ദ്രൻ' }, mantra: 'Om Charaiye Namaha' },
  { id: '65', names: { English: 'Shukra', Hindi: 'शुक्र', Telugu: 'శుక్రుడు', Kannada: 'ಶುಕ್ರ', Tamil: 'சுக்ரன்', Malayalam: 'ശുക്രൻ' }, mantra: 'Om Shukraiye Namaha' },
  { id: '66', names: { English: 'Shani', Hindi: 'शनि', Telugu: 'శని', Kannada: 'ಶನಿ', Tamil: 'சனி', Malayalam: 'ശനി' }, mantra: 'Om Shaniiye Namaha' },
  { id: '67', names: { English: 'Rahu', Hindi: 'राहु', Telugu: 'రాహు', Kannada: 'ರಾಹು', Tamil: 'ராகு', Malayalam: 'രാഹു' }, mantra: 'Om Rahuiye Namaha' },
  { id: '68', names: { English: 'Ketu', Hindi: 'केतु', Telugu: 'కేతు', Kannada: 'ಕೇತು', Tamil: 'கேது', Malayalam: 'കേതു' }, mantra: 'Om Ketuiye Namaha' },
  { id: '69', names: { English: 'Pashupathi', Hindi: 'पशुपति', Telugu: 'పశుపతి', Kannada: 'ಪಶುಪತಿ', Tamil: 'பசுபதி', Malayalam: 'പശുപതി' }, mantra: 'Om Pashupathiiye Namaha' },
  { id: '70', names: { English: 'Venu Gopala', Hindi: 'वेनु गोपाल', Telugu: 'వేణు గోపాలుడు', Kannada: 'ವೇಣು ಗೋಪಾಲ', Tamil: 'வேணு கோபாலன்', Malayalam: 'വേണു ഗോപാലൻ' }, mantra: 'Om Venu Gopalaaiye Namaha' },
  { id: '71', names: { English: 'Vasudha', Hindi: 'वसुधा', Telugu: 'వసుధా', Kannada: 'ವಸುಧಾ', Tamil: 'வசுதா', Malayalam: 'വസുധ' }, mantra: 'Om Vasudhaiye Namaha' },
  { id: '72', names: { English: 'Narada', Hindi: 'नारद', Telugu: 'నారదుడు', Kannada: 'ನಾರದ', Tamil: 'நாரதர்', Malayalam: 'നാരദൻ' }, mantra: 'Om Naradaiye Namaha' },
  { id: '73', names: { English: 'Nandhi', Hindi: 'नंदी', Telugu: 'నంది', Kannada: 'ನಂದಿ', Tamil: 'நந்தி', Malayalam: 'നന്ദി' }, mantra: 'Basava Basava' },
  { id: '74', names: { English: 'Guru Bhruhaspati', Hindi: 'गुरु बृहस्पति', Telugu: 'గురు బృహస్పతి', Kannada: 'ಗುರು ಬೃಹಸ್ಪತಿ', Tamil: 'குரு ப்ருஹஸ்பதி', Malayalam: 'ഗുരു ബൃഹസ്പതി' }, mantra: 'Om Guru Bhruhaspatiaiye Namaha' },
  { id: '75', names: { English: 'Mangala', Hindi: 'मंगल', Telugu: 'మంగళుడు', Kannada: 'ಮಂಗಳ', Tamil: 'மங்களன்', Malayalam: 'മംഗളൻ' }, mantra: 'Om Mangalaya Namaha' },
  { id: '76', names: { English: 'Bhudha', Hindi: 'बुध', Telugu: 'బుధుడు', Kannada: 'ಬುಧ', Tamil: 'புதன்', Malayalam: 'ബുധൻ' }, mantra: 'Om Bhudhaiye Namaha' },
  { id: '77', names: { English: 'Soma', Hindi: 'सोम', Telugu: 'సోముడు', Kannada: 'ಸೋಮ', Tamil: 'சோமன்', Malayalam: 'സോമൻ' }, mantra: 'Om Somaiye Namaha' },
  { id: '78', names: { English: 'Skanda', Hindi: 'स्कंद', Telugu: 'స్కందుడు', Kannada: 'ಸ್ಕಂದ', Tamil: 'ஸ்கந்தன்', Malayalam: 'സ്കന്ദൻ' }, mantra: 'Om Skandaiye Namaha' },
  { id: '79', names: { English: 'Vasukhi', Hindi: 'वासुकी', Telugu: 'వాసుకి', Kannada: 'ವಾಸುಕಿ', Tamil: 'வாசுகி', Malayalam: 'വാസുകി' }, mantra: 'Om Vasukhiiye Namaha' },
  { id: '80', names: { English: 'Anantha', Hindi: 'अनंत', Telugu: 'అనంతుడు', Kannada: 'ಅನಂತ', Tamil: 'அனந்தன்', Malayalam: 'അനന്തൻ' }, mantra: 'Om Ananthaiye Namaha' },
  { id: '81', names: { English: 'Shailaputri', Hindi: 'शैलपुत्री', Telugu: 'శైలపుత్రి', Kannada: 'ಶೈಲಪುತ್ರಿ', Tamil: 'சைலபுத்ரி', Malayalam: 'ശൈലപുത്രി' }, mantra: 'Om Shailaputriiye Namaha' },
  { id: '82', names: { English: 'Brahmacharini', Hindi: 'ब्रह्मचारिणी', Telugu: 'బ్రహ్మచారిణి', Kannada: 'ಬ್ರಹ್ಮಚಾರಿಣಿ', Tamil: 'பிரம்மசாரிணி', Malayalam: 'ബ്രഹ്മചാരിണി' }, mantra: 'Om Brahmachariniiye Namaha' },
  { id: '83', names: { English: 'Chandraganta', Hindi: 'चंद्रघंटा', Telugu: 'చంద్రగంట', Kannada: 'ಚಂದ್ರಘಂಟಾ', Tamil: 'சந்திரகண்டா', Malayalam: 'ചന്ദ്രഗണ്ടാ' }, mantra: 'Om Chandragantaiye Namaha' },
  { id: '84', names: { English: 'Kushmanda', Hindi: 'कुष्मांडा', Telugu: 'కుష్మాండ', Kannada: 'ಕುಷ್ಮಾಂಡಾ', Tamil: 'குஷ்மாண்டா', Malayalam: 'കുഷ്മാണ്ടാ' }, mantra: 'Om Kushmandaiye Namaha' },
  { id: '85', names: { English: 'Skandamata', Hindi: 'स्कंदमाता', Telugu: 'స్కందమాత', Kannada: 'ಸ್ಕಂದಮಾತಾ', Tamil: 'ஸ்கந்தமாதா', Malayalam: 'സ്കന്ദമാതാ' }, mantra: 'Om Skandamata Namaha' },
  { id: '86', names: { English: 'Katyayani', Hindi: 'कात्यायनी', Telugu: 'కాత్యాయనీ', Kannada: 'ಕಾತ್ಯಾಯನಿ', Tamil: 'காத்யாயனி', Malayalam: 'കാത്യായനി' }, mantra: 'Om Katyayaniiye Namaha' },
  { id: '87', names: { English: 'Kalaratri', Hindi: 'कालरात्रि', Telugu: 'కాలరాత్రి', Kannada: 'ಕಾಲರಾತ್ರಿ', Tamil: 'காலராத்திரி', Malayalam: 'കാലരാത്രി' }, mantra: 'Om Kalaratriiye Namaha' },
  { id: '88', names: { English: 'Mahagauri', Hindi: 'महागौरी', Telugu: 'మహాగౌరి', Kannada: 'ಮಹಾಗೌರಿ', Tamil: 'மஹாகௌரி', Malayalam: 'മഹാഗൗരി' }, mantra: 'Om Mahagauriye Namaha' },
  { id: '89', names: { English: 'Siddhidhatri', Hindi: 'सिद्धिदात्री', Telugu: 'సిద్ధిధాత్రి', Kannada: 'ಸಿದ್ಧಿಧಾತ್ರೀ', Tamil: 'சித்திதாத்ரி', Malayalam: 'സിദ്ധിധാത്രി' }, mantra: 'Om Siddhidhatriiye Namaha' },
  { id: '90', names: { English: 'Hayagriva', Hindi: 'हयग्रीव', Telugu: 'హయగ్రీవుడు', Kannada: 'ಹಯಗ್ರೀವ', Tamil: 'ஹயக்ரீவர்', Malayalam: 'ഹയഗ്രീവൻ' }, mantra: 'Om Hayagrivaya Namaha' },
  { id: '91', names: { English: 'Nataraja', Hindi: 'नटराज', Telugu: 'నటరాజు', Kannada: 'ನಟರಾಜ', Tamil: 'நடராஜர்', Malayalam: 'നടരാജൻ' }, mantra: 'Om Natarajaya Namaha' },
  { id: '92', names: { English: 'KanyaKumari', Hindi: 'कन्याकुमारी', Telugu: 'కన్యాకుమారి', Kannada: 'ಕನ್ಯಾಕುಮಾರಿ', Tamil: 'கன்னியாகுமரி', Malayalam: 'കന്ന്യാകുമാരി' }, mantra: 'Om KanyaKumariiye Namaha' },
  { id: '93', names: { English: 'Buddha', Hindi: 'बुद्ध', Telugu: 'బుద్ధుడు', Kannada: 'ಬುದ್ಧ', Tamil: 'புத்தர்', Malayalam: 'ബുദ്ധൻ' }, mantra: 'Buddham Sharanam Gacchami' },
  { id: '94', names: { English: 'Kamakshi', Hindi: 'कामाक्षी', Telugu: 'కామాక్షి', Kannada: 'ಕಾಮಾಕ್ಷಿ', Tamil: 'காமாட்சி', Malayalam: 'കാമാക്ഷി' }, mantra: 'Om Kamakshiiye Namaha' },
  { id: '95', names: { English: 'Bhavani', Hindi: 'भवानी', Telugu: 'భవాని', Kannada: 'ಭವಾನಿ', Tamil: 'பவானி', Malayalam: 'ಭವാനി' }, mantra: 'Om Bhavaniiye Namaha' },
  { id: '96', names: { English: 'Chandra Maulishwara', Hindi: 'चन्द्र मौलीश्वर', Telugu: 'చంద్ర మౌలీశ్వరుడు', Kannada: 'ಚಂದ್ರಮೌಲೀಶ್ವರ', Tamil: 'சந்திரமௌலீஸ்வரர்', Malayalam: 'ചന്ദ്രമൗലീശ്വരൻ' }, mantra: 'Om Namah Shivaya' },
  { id: '97', names: { English: 'Linga', Hindi: 'लिंग', Telugu: 'లింగం', Kannada: 'ಲಿಂಗ', Tamil: 'லிங்கம்', Malayalam: 'ലിംഗം' }, mantra: 'Om Namah Shivaya' },
  { id: '98', names: { English: 'Timmappa', Hindi: 'तिम्मप्पा', Telugu: 'తిమ్మప్ప', Kannada: 'ತಿಮ್ಮಪ್ಪ', Tamil: 'திம்மப்பா', Malayalam: 'തിമ്മಪ್ಪ' }, mantra: 'Govinda Govinda' },
  { id: '99', names: { English: 'Balaji', Hindi: 'बालाजी', Telugu: 'బాలాజీ', Kannada: 'ಬಾಲಾಜಿ', Tamil: 'பாலாஜி', Malayalam: 'ബാലാജി' }, mantra: 'Govinda Govinda' },
  { id: '100', names: { English: 'Rajalaxmi', Hindi: 'राजलक्ष्मी', Telugu: 'రాజలక్ష్మి', Kannada: 'ರಾಜಲಕ್ಷ್ಮೀ', Tamil: 'ராஜலக்ஷ்மி', Malayalam: 'രാജലക്ഷ്മി' }, mantra: 'Om Rajalaxmiiye Namaha' },
  { id: '101', names: { English: 'Sharadha', Hindi: 'शारदा', Telugu: 'శారద', Kannada: 'ಶಾರದಾ', Tamil: 'சாரதா', Malayalam: 'शारदा' }, mantra: 'Om Sharadhaiye Namaha' },
  { id: '102', names: { English: 'Parameshwari', Hindi: 'परमेश्वरी', Telugu: 'పరమేశ్వరి', Kannada: 'ಪರಮೇಶ್ವರಿ', Tamil: 'பரமேஸ்வரி', Malayalam: 'പരമേശ്വരി' }, mantra: 'Om Parameshwariiye Namaha' },
  { id: '103', names: { English: 'Hari', Hindi: 'हरि', Telugu: 'హరి', Kannada: 'ಹರಿ', Tamil: 'ஹரி', Malayalam: 'ഹരി' }, mantra: 'Hari Om Hari Om' },
  { id: '104', names: { English: 'Bhola', Hindi: 'भोला', Telugu: 'భోలా', Kannada: 'ಭೋಲಾ', Tamil: 'போலா', Malayalam: 'ഭോളാ' }, mantra: 'Om Namah Shivaya' },
  { id: '105', names: { English: 'Ayyappa', Hindi: 'अय्यप्पा', Telugu: 'అయ్యప్ప', Kannada: 'ಅಯ್ಯಪ್ಪ', Tamil: 'அய்யப்பன்', Malayalam: 'അയ്യപ്പൻ' }, mantra: 'Swamiyee Sharanam Ayyappa' },
  { id: '106', names: { English: 'Manikanta', Hindi: 'मणिकांत', Telugu: 'మణికాంత', Kannada: 'ಮಣಿಕಾಂತ', Tamil: 'மணிகண்டன்', Malayalam: 'മണികണ്ഠൻ' }, mantra: 'Swamiyee Sharanam Ayyappa' },
  { id: '107', names: { English: 'Parameshwara', Hindi: 'परमेश्वर', Telugu: 'పరమేశ్వరుడు', Kannada: 'ಪರಮೇಶ್ವರ', Tamil: 'பரமேஸ்வரன்', Malayalam: 'പരമേശ്വരൻ' }, mantra: 'Om Parameshwaraiye Namaha' },
  { id: '108', names: { English: 'Shivani', Hindi: 'शिवानी', Telugu: 'శివాని', Kannada: 'ಶಿವಾನಿ', Tamil: 'சிவானி', Malayalam: 'ശിവാനി' }, mantra: 'Om Shivaniiye Namaha' },
  { id: '109', names: { English: 'Sastha', Hindi: 'शास्ता', Telugu: 'శాస్తా', Kannada: 'ಶಾಸ್ತಾ', Tamil: 'சாஸ்தா', Malayalam: 'ശാസ്താ' }, mantra: 'Swamiyee Sharanam Ayyappa' },
  { id: '110', names: { English: 'Gajanan', Hindi: 'गजानन', Telugu: 'గజాననుడు', Kannada: 'ಗಜಾನನ', Tamil: 'கஜானன்', Malayalam: 'ഗജാനൻ' }, mantra: 'Ganapathi pappa Moriya' },
  { id: '111', names: { English: 'Srinivasa', Hindi: 'श्रीनिवास', Telugu: 'శ్రీనివాస', Kannada: 'ಶ್ರೀನಿವಾಸ', Tamil: 'ஸ்ரீனிவாசன்', Malayalam: 'ശ്രീനിവാസൻ' }, mantra: 'Govinda Govinda' },
  { id: '112', names: { English: 'Maruti', Hindi: 'मारुति', Telugu: 'మారుతి', Kannada: 'ಮಾರುತಿ', Tamil: 'மாருதி', Malayalam: 'മാരുതി' }, mantra: 'Jai Jai Maruti' },
  { id: '113', names: { English: 'Vittala', Hindi: 'विट्ठल', Telugu: 'విఠల', Kannada: 'ವಿಠಲ', Tamil: 'விட்டலா', Malayalam: 'വിഠല' }, mantra: 'Vittala Vittala' },
  { id: '114', names: { English: 'Jagannatha', Hindi: 'जगन्नाथ', Telugu: 'జగన్నాథ', Kannada: 'ಜಗನ್ನಾಥ', Tamil: 'ஜகன்னாதர்', Malayalam: 'ജഗന്നാഥൻ' }, mantra: 'Om Jagannathaiye Namaha' },
  { id: '115', names: { English: 'Sadashiva', Hindi: 'सदाशिव', Telugu: 'సదాశివ', Kannada: 'ಸದಾಶಿವ', Tamil: 'சதாசிவன்', Malayalam: 'സദാശിവൻ' }, mantra: 'Om Sadashivaiye Namaha' },
  { id: '116', names: { English: 'Govardhana', Hindi: 'गोवर्धन', Telugu: 'గోవర్ధన', Kannada: 'ಗೋವರ್ಧನ', Tamil: 'கோவர்த்தனா', Malayalam: 'ഗോവർദ്ധന' }, mantra: 'Govardhana Gopala' },
  { id: '117', names: { English: 'Ranga', Hindi: 'रंगा', Telugu: 'రంగా', Kannada: 'ರಂಗ', Tamil: 'ரங்கா', Malayalam: 'രംഗ' }, mantra: 'Rangaa Rangaa' },
  { id: '118', names: { English: 'Madhava', Hindi: 'माधव', Telugu: 'మాధవ', Kannada: 'ಮಾಧವ', Tamil: 'மாதவா', Malayalam: 'മാധവ' }, mantra: 'Madhava Madhava' },
  { id: '119', names: { English: 'Keshava', Hindi: 'केशव', Telugu: 'కేశవ', Kannada: 'ಕೇಶವ', Tamil: 'கேசவா', Malayalam: 'കേശവ' }, mantra: 'Keshava Keshava' },
  { id: '120', names: { English: 'Gayatri', Hindi: 'गायत्री', Telugu: 'గాయత్రి', Kannada: 'ಗಾಯತ್ರಿ', Tamil: 'காயத்ரி', Malayalam: 'ഗായത്രി' }, mantra: 'Om Gayatriiye Namaha' },
  { id: '121', names: { English: 'Ekadhantha', Hindi: 'एकदंत', Telugu: 'ఏకదంత', Kannada: 'ಏಕದಂತ', Tamil: 'ஏகதந்தா', Malayalam: 'ഏകദന്ത' }, mantra: 'Ganapathi pappa Moriya' },
  { id: '122', names: { English: 'Tara Maa', Hindi: 'तारा मां', Telugu: 'తారా మాత', Kannada: 'ತಾರಾ ಮಾ', Tamil: 'தாரா மா', Malayalam: 'താരാ മാ' }, mantra: 'Jai Tara Maa' },
  { id: '123', names: { English: 'SitaRama', Hindi: 'सीताराम', Telugu: 'సీతారామ', Kannada: 'ಸೀತಾರಾಮ', Tamil: 'சீதாராம', Malayalam: 'സീതാരാമ' }, mantra: 'Jai Siya Ram' },
  { id: '124', names: { English: 'SimhaChalam', Hindi: 'सिम्हाचलम', Telugu: 'సింహాచలం', Kannada: 'ಸಿಂಹಾಚಲಂ', Tamil: 'சிம்மாச்சலம்', Malayalam: 'സിംഹാചലം' }, mantra: 'Om Shimhachaleshwaraya Namaha' },
  { id: '125', names: { English: 'Tirupathi', Hindi: 'तिरुपति', Telugu: 'తిరుపతి', Kannada: 'ತಿರುಪತಿ', Tamil: 'திருப்பதி', Malayalam: 'തിരുപ്പതി' }, mantra: 'Govinda Govinda' },
  { id: '126', names: { English: 'Padmanabha Swamy', Hindi: 'पद्मनाभ स्वामी', Telugu: 'పద్మనాభ స్వామి', Kannada: 'ಪದ್ಮನಾಭ ಸ್ವಾಮಿ', Tamil: 'பத்மநாப சுவாமி', Malayalam: 'പത്മനാഭ സ്വാമി' }, mantra: 'Govinda Govinda' },
  { id: '127', names: { English: 'Guruvayur Krishna', Hindi: 'गुरुवायूर कृष्ण', Telugu: 'గురువాయూర్ కృష్ణ', Kannada: 'ಗುರುವಾಯೂರು ಕೃಷ್ಣ', Tamil: 'குருவாயூர் கிருஷ்ணா', Malayalam: 'ഗുരുവായൂർ കൃഷ്ണ' }, mantra: 'Krishna Krishna' },
  { id: '128', names: { English: 'Udupi Krishna', Hindi: 'उडुपी कृष्ण', Telugu: 'ఉడిపి కృష్ణ', Kannada: 'ಉಡುಪಿ ಕೃಷ್ಣ', Tamil: 'உடுப்பி கிருஷ்ணா', Malayalam: 'ഉഡുപ്പി കൃഷ്ണ' }, mantra: 'Krishna Krishna' },
  { id: '129', names: { English: 'Sridhara', Hindi: 'श्रीधर', Telugu: 'శ్రీధర', Kannada: 'ಶ್ರೀಧರ', Tamil: 'ஸ்ரீதரா', Malayalam: 'ശ്രീധര' }, mantra: 'Om Sridharaiye Namaha' },
  { id: '130', names: { English: 'Upendra', Hindi: 'उपेन्द्र', Telugu: 'ఉపేంద్ర', Kannada: 'ಉಪೇಂದ್ರ', Tamil: 'உபேந்திரா', Malayalam: 'ഉപേന്ദ്ര' }, mantra: 'Om Upendraiye Namaha' },
  { id: '131', names: { English: 'Madhusudhana', Hindi: 'मधुसूदन', Telugu: 'మధుసూధన', Kannada: 'ಮಧುಸೂಧನ', Tamil: 'மதுசூதனா', Malayalam: 'മധുസൂദന' }, mantra: 'Om Madhusudhanaiye Namaha' },
  { id: '132', names: { English: 'Trivikrama', Hindi: 'त्रिविक्रम', Telugu: 'త్రివిక్రమ', Kannada: 'ತ್ರಿವಿಕ್ರಮ', Tamil: 'திரிவிக்ரமா', Malayalam: 'ത്രിവിക്രമ' }, mantra: 'Om Trivikramaiye Namaha' },
  { id: '133', names: { English: 'Domodhara', Hindi: 'दामोदर', Telugu: 'దామోదర', Kannada: 'ದಾಮೋದರ', Tamil: 'தாமோதரா', Malayalam: 'ദാമോദര' }, mantra: 'Om Domodharaiye Namaha' },
  { id: '134', names: { English: 'Vasudeva', Hindi: 'वासुदेव', Telugu: 'వాసుదేవ', Kannada: 'ವಾಸುದೇವ', Tamil: 'வாசுதேவா', Malayalam: 'വാസുദേവ' }, mantra: 'Om Vasudevaiye Namaha' },
  { id: '135', names: { English: 'Adhokshaja', Hindi: 'अधोक्षज', Telugu: 'అధోక్షజ', Kannada: 'ಅಧೋಕ್ಷಜ', Tamil: 'அதோக்ஷஜா', Malayalam: 'അധോക്ഷജ' }, mantra: 'Om Adhokshajaiye Namaha' },
  { id: '136', names: { English: 'Janardhana', Hindi: 'जनार्दन', Telugu: 'జనార్ధన', Kannada: 'ಜನಾರ್ದನ', Tamil: 'ஜனார்த்தனா', Malayalam: 'ജനാർദ്ദന' }, mantra: 'Om Janardhanaiye Namaha' },
  { id: '137', names: { English: 'Hrishikesha', Hindi: 'हृषिकेश', Telugu: 'హృషీకేశ', Kannada: 'ಹೃಷೀಕೇಶ', Tamil: 'ரிஷிகேசா', Malayalam: 'ഹൃഷീകേശ' }, mantra: 'Om Hrishikeshaiye Namaha' },
  { id: '138', names: { English: 'Sankarushana', Hindi: 'संकर्षण', Telugu: 'సంకర్షణ', Kannada: 'ಸಂಕರ್ಷಣ', Tamil: 'சங்கர்ஷணா', Malayalam: 'സങ്കർഷണ' }, mantra: 'Om  Sankarshaiye Namaha' },
  { id: '139', names: { English: 'Pradhyumna', Hindi: 'प्रद्युम्न', Telugu: 'ప్రద్యుమ్న', Kannada: 'ಪ್ರದ್ಯುಮ್ನ', Tamil: 'பிரத்யும்னா', Malayalam: 'പ്രദ്യുമ്ന' }, mantra: 'Om Pradhyumnaiye Namaha' },
  { id: '140', names: { English: 'Anirudhha', Hindi: 'अनिरुद्ध', Telugu: 'అనిరుద్ధ', Kannada: 'ಅನಿರುದ್ಧ', Tamil: 'அனிருத்தா', Malayalam: 'അനിരുദ്ധ' }, mantra: 'Om Anirudhhaiye Namaha' },
  { id: '141', names: { English: 'Purushothama', Hindi: 'पुरुषोत्तम', Telugu: 'పురుషోత్తమ', Kannada: 'ಪುರುಷೋತ್ತಮ', Tamil: 'புருஷோத்தமா', Malayalam: 'പുരുഷോത്തമ' }, mantra: 'Om Purushothamaiye Namaha' },
  { id: '142', names: { English: 'Mukunda', Hindi: 'मुकुंद', Telugu: 'ముకుంద', Kannada: 'ಮುಕುಂದ', Tamil: 'முகுந்தா', Malayalam: 'മുകുന്ദ' }, mantra: 'Om Mukundaiye Namaha' },
  { id: '143', names: { English: 'Achuta', Hindi: 'अच्युत', Telugu: 'అచ్యుత', Kannada: 'ಅಚ್ಯುತ', Tamil: 'அச்சுதா', Malayalam: 'അച്യുത' }, mantra: 'Om Achutaiye Namaha' },
  { id: '144', names: { English: 'RadhaKrishna', Hindi: 'राधाकृष्ण', Telugu: 'రాధాకృష్ణ', Kannada: 'ರಾಧಾಕೃಷ್ಣ', Tamil: 'ராதாகிருஷ்ணா', Malayalam: 'രാധാകൃഷ്ണ' }, mantra: 'Radhe Radhe' },
  { id: '145', names: { English: 'Pundarikaksha', Hindi: 'पुंडरीकाक्ष', Telugu: 'పుండరీకాక్ష', Kannada: 'ಪುಂಡರೀಕಾಕ್ಷ', Tamil: 'புண்டரீகாக்ஷ', Malayalam: 'പുണ്ഡരീകാക്ഷ' }, mantra: 'Om Pundarikashaiye Namaha' },
  { id: '146', names: { English: 'Vedagarbha', Hindi: 'वेदगर्भ', Telugu: 'వేదగర్భ', Kannada: 'ವೇದಗರ್ಭ', Tamil: 'வேதகர்பா', Malayalam: 'വേദഗർഭ' }, mantra: 'Om Vedagarbhaiye Namaha' },
  { id: '147', names: { English: 'VedaVyasa', Hindi: 'वेदव्यास', Telugu: 'వేదవ్యాస', Kannada: 'ವೇದವ್ಯಾಸ', Tamil: 'வேதவியாசா', Malayalam: 'വേദവ്യാസ' }, mantra: 'Om VedaVyasaiye Namaha' },
  { id: '148', names: { English: 'Vishwanatha', Hindi: 'विश्वनाथ', Telugu: 'విశ్వనాథ', Kannada: 'ವಿಶ್ವನಾಥ', Tamil: 'விஸ்வநாதா', Malayalam: 'വിശ്വനാഥ' }, mantra: 'Om Vishwanathaiye Namaha' },
  { id: '149', names: { English: 'Bhootanatha', Hindi: 'भूतनाथ', Telugu: 'భూతనాథ', Kannada: 'ಭೂತನಾಥ', Tamil: 'பூதநாதா', Malayalam: 'ഭൂതനാഥ' }, mantra: 'Om Bhootanathaiye Namaha' },
  { id: '150', names: { English: 'Shyama', Hindi: 'श्याम', Telugu: 'శ్యామ', Kannada: 'ಶ್ಯಾಮ', Tamil: 'ஷ்யாமா', Malayalam: 'ശ്യാമ' }, mantra: 'Shyama Shyama' }
];

export const INITIAL_CHAT_MESSAGE = "Namaste! I am your guide to Hindu mythology. Ask me anything about the gods, their stories, or the quiz images.";

interface DifficultyConfig {
  options: number;
  points: number;
  label: string;
  rounds: number;
}

export const DIFFICULTY_SETTINGS: Record<Difficulty, DifficultyConfig> = {
  easy: { options: 2, points: 10, label: "Easy", rounds: 10 },
  medium: { options: 4, points: 20, label: "Medium", rounds: 27 },
  hard: { options: 4, points: 30, label: "Hard", rounds: 54 }
};
